[package]
name = "tally"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "1", features = ["system-tray", "dialog-all", "shell-open", "notification-all"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
axum = "0.7"
parking_lot = "0.12"
once_cell = "1"
uuid = { version = "1", features = ["v4", "serde"] }
thiserror = "1"
time = "0.3"

[build-dependencies]
tauri-build = { version = "1" }
